print("Welcome!!")
print("Enter the first number: ")
a=input()
print("Enter the second number: ")
b=input()
print("Addition: ", int(a+b))
print("Subtraction: ", int(a)-int(b))
print("Multiplication: ", int(a)*int(b))
print("Division: ", int(a)/int(b))