print("This program will show you the maximum and minimum number amoung four numbers")
print("Enter the first number")
a = int(input())
print("Enter the second number")
b = int(input())
print("Enter the third number")
c = int(input())
print("Enter the fourth number")
d = int(input())
list = [a , b , c, d]
print(max(list), "is the maximum number")
print(min(list), "is the minimum number")